---
- name: Install hostapd  (state=present is optional)
  apt:
    name: hostapd
    state: present

- name: Install bridge-utils  (state=present is optional)
  apt:
    name: bridge-utils
    state: present

- name: stop service hostapd on debian, if running
  systemd:
    name: hostapd
    state: stopped

- name: dhcpcd denyinterfaces wlan0
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^denyinterfaces wlan0'
    line: denyinterfaces wlan0

- name: dhcpcd denyinterfaces eth0
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^denyinterfaces eth0'
    line: denyinterfaces eth0

- name: write bridge-br0.netdev
  copy:
    dest: "/etc/systemd/network/bridge-br0.netdev"
    content: |
      [NetDev]
      Name=br0
      Kind=bridge

- name: write bridge-br0-slave.network
  copy:
    dest: "/etc/systemd/network/bridge-br0-slave.network"
    content: |
      [Match]
      Name=eth0
      [Network]
      Bridge=br0

- name: write bridge-br0-slave.network
  copy:
    dest: "/etc/systemd/network/bridge-br0.network"
    content: |
      [Match]
      Name=br0
      [Network]
      Address=192.168.10.100/24
      Gateway=192.168.10.1
      DNS=8.8.8.8

- name: write hostapd.conf
  copy:
    dest: "/etc/hostapd/hostapd.conf"
    content: |
      interface=wlan0
      bridge=br0
      ssid=ChezWaKaNt
      hw_mode=g
      channel=7
      wmm_enabled=0
      macaddr_acl=0
      ignore_broadcast_ssid=0
      wpa=2
      wpa_passphrase=quatrequatre
      wpa_key_mgmt=WPA-PSK
      wpa_pairwise=TKIP
      rsn_pairwise=CCMP

- name: unmask hostapd
  systemd:
    name: hostapd
    masked: no
    enabled: yes
    state: started

- name: check if br0 exist
  shell: brctl show | grep br0 | awk '{print $6}' | wc -l
  register: countBr0tBridgesDevices

- name: brctl addbr br0
  shell: brctl addbr br0
  when: countBr0tBridgesDevices.stdout.find('0') != -1

- name: addif br0 eth0 check si plusieurs lancement
  shell: brctl addif br0 eth0

- name: restart systemd-network
  systemd:
    name: systemd-network
    state: restarted
