---
- name: Install hostapd  (state=present is optional)
  apt:
    name: hostapd
    state: present

- name: Install bridge-utils  (state=present is optional)
  apt:
    name: bridge-utils
    state: present

- name: stop service hostapd on debian, if running
  systemd:
    name: hostapd
    state: stopped

- name: check if br0 exist
  shell: brctl show | grep br0 | awk '{print $6}' | wc -l
  register: countBr0tBridgesDevices

- name: brctl addbr br0
  shell: brctl addbr br0
  when: countBr0tBridgesDevices.stdout.find('0') != -1

- name: write hostapd.conf
  copy:
    dest: "/etc/hostapd/hostapd.conf"
    content: |
      interface=wlan0
      bridge=br0
      ssid=ChezWaKaNt
      hw_mode=g
      channel=7
      wmm_enabled=0
      macaddr_acl=0
      ignore_broadcast_ssid=0
      wpa=2
      wpa_passphrase=quatre
      wpa_key_mgmt=WPA-PSK
      wpa_pairwise=TKIP
      rsn_pairwise=CCMP

- name: uncomment DEAMON_CONF in hostapd
  lineinfile:
    path: /etc/default/hostapd
    regexp: '^#DEAMON_CONF="/etc/hostapd/hostapd.conf"'
    line: DEAMON_CONF="/etc/hostapd/hostapd.conf"

- name: network interfaces allow-hotplug wlan0
  lineinfile:
    path: /etc/network
    regexp: '^allow-hotplug wlan0'
    line: allow-hotplug wlan0

- name: network interfaces iface  wlan0 inet manual
  lineinfile:
    path: /etc/network
    regexp: '^iface  wlan0 inet manual'
    line: iface wlan0 inet manual
    
- name: network interfaces auto br0
  lineinfile:
    path: /etc/network
    regexp: '^auto br0'
    line: auto br0

- name: network iface wlan0 inet dhcp
  lineinfile:
    path: /etc/network
    regexp: '^iface wlan0 inet dhcp'
    line: iface wlan0 inet dhcp

- name: network iface bridge_ports eth0 wlan0
  lineinfile:
    path: /etc/network
    regexp: '^bridge_ports eth0 wlan0'
    line: bridge_ports eth0 wlan0

- name: dhcpcd denyinterfaces wlan0
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^denyinterfaces wlan0'
    line: denyinterfaces wlan0

- name: dhcpcd denyinterfaces eth0
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: '^denyinterfaces eth0'
    line: denyinterfaces eth0

- name: addif br0 eth0 check si plusieurs lancement
  shell: brctl addif br0 eth0
