---
- name: Install hostapd  (state=present is optional)
  apt:
    name: hostapd
    state: present

- name: Install bridge-utils  (state=present is optional)
  apt:
    name: bridge-utils
    state: present

- name: stop service hostapd on debian, if running
  systemd:
    name: hostapd
    state: stopped

- name: brctl addbr br0
  shell: brctl addbr br0