---
- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the latest packages'
  action: apt upgrade=safe

- name: 'Remove all dependenices no longer required'
  shell: apt-get autoremove

- name: 'rfkill unlock'
  shell: rfkill unblock all
  
- name: Install hostapd  (state=present is optional)
  apt:
    name: hostapd
    state: present

- name: Install bridge-utils  (state=present is optional)
  apt:
    name: bridge-utils
    state: present

- name: stop service hostapd on debian, if running
  systemd:
    name: hostapd
    state: stopped
