---
- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the latest packages'
  action: apt upgrade=safe

- name: 'Remove all dependenices no longer required'
  shell: apt-get autoremove

- name: 'rpi-update'
  shell: rpi-update  

- name: 'rfkill unlock'
  shell: rfkill unblock all
  